### ISSUE TITLE
Extension not working with Vitest 2.1.5

### ISSUE THREAD

**Issue by sumomo015** [vitest-dev/vscode#530]
### Describe the bug

The VS Code extension for Vitest is not functioning as expected with Vitest version 2.1.5. The extension worked correctly with previous versions of Vitest, but after upgrading to 2.1.5, it seems to have stopped working.

### Reproduction

https://github.com/sumomo015/vitest-vscode-2.1.5

Try to run or debug a test.

### Output

```shell
[18:19:20] Initiating deferred test run
[INFO 18:19:20] Running all tests in vitest-vscode-2.1.5
[Error 18:19:20] Failed to run tests [Error TypeError] this.ctx.initBrowserProviders is not a function
TypeError: this.ctx.initBrowserProviders is not a function
    at e.runTests (/Users/me/.vscode/extensions/vitest.explorer-1.6.6/dist/worker.js:21:2432)
    at process.S (/Users/me/.vscode/extensions/vitest.explorer-1.6.6/dist/worker.js:8:28753)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:950:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
[18:19:20] Ending test run <none>
```

### Version

1.6.6

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sumomo015** [comment]
@sheremet-va 

Thank you for fixing this issue! I have confirmed that it is resolved in version 1.6.7.
Your prompt response and support are greatly appreciated. 🙏
