### ISSUE TITLE
Regression: Extension 1.28.0 breaks module path resolution on Windows (C:/ vs D:/ drives)

### ISSUE THREAD

**Issue by christoph-hue** [vitest-dev/vscode#653]
### Describe the bug

{"content":"Starting with extension version 1.28.0 (released today), the Vitest VSCode extension incorrectly attempts to resolve modules on Windows using the C: drive (e.g., C:\\Projects\\appmod\\...) even when the project is actually located on D: (e.g., D:\\Projects\\appmod\\...).\n\nThis causes Vitest to fail to start with ERR_MODULE_NOT_FOUND errors for paths that never existed on C:. Reverting to extension version 1.26.4 immediately resolves the problem and restores correct module resolution.\n\nNo manual migration or project move ever occurred. The project has always been on D:. This appears to be a regression or breaking change in 1.28.0.","label":"Describe the bug"}

### Reproduction

{"content":"1. Open a workspace folder on D: drive (e.g., D:\\Projects\\appmod\\frontend\\omnibuild-ng) in VS Code.\n2. Ensure Vitest and the extension (1.28.0) are installed.\n3. Attempt to run tests via Vitest Explorer.\n4. Observe errors indicating modules cannot be found on C:\\..., even though all project files are on D:.\n\nReverting the extension to version 1.26.4 fixes the issue.","label":"Reproduction"}

### Output

```shell
{"content":"[INFO] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.\n[INFO] Running Vitest v3.2.4 with \"C:\\Program Files\\nodejs\\node.EXE C:/Users/Chris/.vscode/extensions/vitest.explorer-1.28.0/dist/worker.js\"\n[Error] Vitest failed to start:\nError [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\\Projects\\appmod\\frontend\\omnibuild-ng\\node_modules\\vitest\\dist\\node.js' imported from C:\\Users\\Chris\\.vscode\\extensions\\vitest.explorer-1.28.0\\dist\\worker.js\n\n(Works fine with extension v1.26.4)","label":"Output"}
```

### Extension Version

{"content":"1.28.0 (bug), 1.26.4 (works)","label":"Extension Version"}

### Vitest Version

{"content":"3.2.4","label":"Vitest Version"}

### Validations

- [x] Check that you are using the latest version of the extension
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Try 1.28.1
